TOP = ..
include $(TOP)/configure/CONFIG
ARCH = $(EPICS_HOST_ARCH)
TARGETS = envPaths
ENGINEER="Brad Webb"
LOCATION="ics-srv-softioc"
include $(TOP)/configure/RULES.ioc
#include $(IOC_COMMON)/configure/RULES.iocBoot.soft


